import type { Metadata } from "next";
import { Cormorant_Garamond, Plus_Jakarta_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { HttpProvider } from "@/contexts/HttpProvider";
import { ToastProvider } from "@/contexts/ToastContext";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-title",
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
});

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${cormorantGaramond.variable} ${geist.variable} antialiased`}
      >
        <HttpProvider>
          <ToastProvider>{children}</ToastProvider>
        </HttpProvider>
      </body>
    </html>
  );
}
